runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_NAME: FlipIt
  APP_ENV: production
  APP_URL: https://myflipitassistant.com
  APP_KEY: base64:t0fqjkhfMu+ajhmVvlL7cDzwVl6TptXuGpx9U5bFMio=
  APP_DEBUG: true
  APP_LOCALE: en
  APP_VERSION: 7.0.3
  PURCHASE_CODE: 5a8327e0-3a9c-b325-c81b-e24891dfba6c
  FORCE_HTTPS: false
  IMAGE_DRIVER: gd
  FILESYSTEM_DRIVER: gcs
  CACHE_PREFIX: lc_
  QUEUE_CONNECTION: sync
  CACHE_DRIVER: database
  SESSION_DRIVER: cookie
  SESSION_LIFETIME: 10080
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PORT: 587
  MAIL_USERNAME: apikey
  MAIL_PASSWORD: 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
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: info@flipit.com
  MAIL_FROM_NAME: FlipIT

  FACEBOOK_CLIENT_ID: 300563050773504
  FACEBOOK_CLIENT_SECRET: 06420c5dd8363b4ce9354f2970221985

  TWITTER_CLIENT_ID: dRnX7jQvuzrFqedzY5U0VcCjf
  TWITTER_CLIENT_SECRET: QB43PccU4FGR8J1YegCUqHrXnVDHMou3pfp3zMYK79ewupWjYA

  GOOGLE_CLIENT_ID: 421161711671-ktpsd6qrvmc00it9n48op5npo7a5l26f.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 4uTwqP_Cbk15QzdqLlYy7pnW

  LOG_CHANNEL: stackdriver
  LOG_LEVEL: debug
  LOG_DAYS: 2

  DISABLE_PHONE: false
  DISABLE_EMAIL: false
  DISABLE_USERNAME: true
  ## Set these environment variables according to your CloudSQL configuration.
  DB_CHARSET: utf8
  DB_COLLATION: utf8_unicode_ci
  DB_DATABASE: flipit
  DB_USERNAME: root
  DB_PASSWORD: flipit
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/flipit-app:us-central1:flipit"
  GOOGLE_CLOUD_PROJECT_ID: flipit-app
  GOOGLE_CLOUD_STORAGE_BUCKET: flipit-app
  GOOGLE_CLOUD_STORAGE_API_URI: https://storage.googleapis.com/flipit-app
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|mp4|json|xml|txt|key|woff2|woff|ttf|eot|svg))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|mp4|json|xml|txt|key|woff2|woff|ttf|eot|svg)$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
