runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_NAME: FlipIt
  APP_ENV: development
  APP_URL: https://flipit-app.uc.r.appspot.com
  APP_KEY: base64:t0fqjkhfMu+ajhmVvlL7cDzwVl6TptXuGpx9U5bFMio=
  APP_DEBUG: true
  APP_LOCALE: en
  APP_VERSION: 7.0.3
  PURCHASE_CODE: 5a8327e0-3a9c-b325-c81b-e24891dfba6c
  FORCE_HTTPS: false
  IMAGE_DRIVER: gd
  CACHE_DRIVER: file
  CACHE_PREFIX: lc_
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: 10080
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PORT: 465
  MAIL_USERNAME: apikey
  MAIL_PASSWORD: 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
  MAIL_ENCRYPTION: ssl
  MAIL_FROM_ADDRESS: info@flipit.com
  MAIL_FROM_NAME: FlipIT

  FACEBOOK_CLIENT_ID: 300563050773504
  FACEBOOK_CLIENT_SECRET: 06420c5dd8363b4ce9354f2970221985

  TWITTER_CLIENT_ID: dRnX7jQvuzrFqedzY5U0VcCjf
  TWITTER_CLIENT_SECRET: QB43PccU4FGR8J1YegCUqHrXnVDHMou3pfp3zMYK79ewupWjYA

  GOOGLE_CLIENT_ID: 643346828791-uagv6iuame038mu32suip9rvt7c5aodn.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: G1jpvqErPtti3COBLTVmeqFo

  LOG_CHANNEL: daily
  LOG_LEVEL: debug
  LOG_DAYS: 2

  DISABLE_PHONE: false
  DISABLE_EMAIL: false
  DISABLE_USERNAME: true
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: hen
  DB_USERNAME: root
  DB_PASSWORD: ToToCap
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/heny-appp:europe-west2:hey"
  GOOGLE_CLOUD_PROJECT_ID: flipit-app
  GOOGLE_CLOUD_STORAGE_BUCKET: flipit-app
  GOOGLE_CLOUD_STORAGE_API_URI: https://storage.googleapis.com/flipit-app
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|mp4|json|xml|txt|key))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|mp4|json|xml|txt|key)$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
